Models/ArticleViewModel.cs
using PersonalBlog.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalBlog.Models
{
    public class ArticleViewModel
    {
    
        public Article Article { get; set; }
        public IList<string> Tags { get; set; }
        public IList<Comment> Comments { get; set; }

    }
}

Areas/Admin/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PersonalBlog.Areas.Admin.Models;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using PersonalBlog.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticleController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;

        public ArticleController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var article = id == default ? new Article() : dataManager.Articles.GetArticleById(id);
           
            var categoryes = dataManager.Categoryes.GetCategoryes();
            var selectCategoryes = new SelectList(categoryes, "Id", "Name");
            var tags = dataManager.ArticleWithTags.GetTagsByArticleId(id);

            EditViewModel viewModel = new EditViewModel
            {
                Article = article,
                Categoryes = selectCategoryes,
                Tags = tags
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(Article article, IFormFile titleImageFile, String tagsStr)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    StaticFilesService staticFilesService = new StaticFilesService(hostingEnvironment);
                    article.TitleImagePath = staticFilesService.SaveFile(titleImageFile, "images/");                
                }
                dataManager.Articles.SaveArticle(article);

                var tags = tagsStr.Split(",");

                List<ArticleWithTags> tagList = new List<ArticleWithTags>();
                foreach(var tag in tags)
                {
                    var articleWithTags = new ArticleWithTags
                    {
                        ArticleId = article.Id,
                        TagName = tag
                    };

                    tagList.Add(articleWithTags);
                }

                dataManager.ArticleWithTags.SaveTags(tagList);

                return RedirectToAction("Articles", "Home");
            }
            return View(article);
        }

        public IActionResult Delete(int id)
        {
            dataManager.Articles.DeleteArticleById(id);
            return RedirectToAction("Articles", "Home");
        }

        public IActionResult DeleteComment(int id)
        {
            dataManager.Comments.DeleteCommentById(id);
            return RedirectToAction("Comments", "Home");
        }
    }
}

Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using PersonalBlog.Data.Entities;

namespace PersonalBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public HomeController(DataManager dataManager, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.dataManager = dataManager;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult Index()
        {
            if(!User.IsInRole("admin"))
            {
                return NotFound();
            }

            return View(userManager.Users.ToList());
        }

        public IActionResult Comments()
        {
            return View(dataManager.Comments.GetComments());
        }
    }
}

Areas/User/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PersonalBlog.Areas.User.Models;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using PersonalBlog.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace PersonalBlog.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly UserManager<ApplicationUser> userManager;

        public ArticleController(DataManager dataManager, IWebHostEnvironment hostingEnvironment, UserManager<ApplicationUser> userManager)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var article = id == default ? new Article() : dataManager.Articles.GetArticleById(id);

            var categoryes = dataManager.Categoryes.GetCategoryes();
            var selectCategoryes = new SelectList(categoryes, "Id", "Name");
            var tags = dataManager.ArticleWithTags.GetTagsByArticleId(id);

            EditViewModel viewModel = new EditViewModel
            {
                Article = article,
                Categoryes = selectCategoryes,
                Tags = tags
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(Article article, IFormFile titleImageFile, string tagsStr)
        {
            if(String.IsNullOrEmpty(article.AuthorId))
            {
                article.AuthorId = userManager.GetUserId(User);
            }

            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    StaticFilesService staticFilesService = new StaticFilesService(hostingEnvironment);
                    article.TitleImagePath = staticFilesService.SaveFile(titleImageFile, "images/");
                }
                dataManager.Articles.SaveArticle(article);

                var tags = tagsStr.Split(",");

                List<ArticleWithTags> tagList = new List<ArticleWithTags>();
                foreach (var tag in tags)
                {
                    var articleWithTags = new ArticleWithTags
                    {
                        ArticleId = article.Id,
                        TagName = tag
                    };

                    tagList.Add(articleWithTags);
                }

                dataManager.ArticleWithTags.SaveTags(tagList);

                return RedirectToAction("Articles", "Home");
            }
            return View(article);
        }

        public IActionResult Delete(int id)
        {
            dataManager.Articles.DeleteArticleById(id);
            return RedirectToAction("Articles", "Home");
        }

        public IActionResult DeleteComment(int id)
        {
            dataManager.Comments.DeleteCommentById(id);
            return RedirectToAction("Comments", "Home");
        }
    }
}

Areas/User/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace PersonalBlog.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly DataManager dataManager;

        public CategoryController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var category = id == default ? new Category() : dataManager.Categoryes.GetCategoryById(id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                dataManager.Categoryes.SaveCategory(category);
                return RedirectToAction("Categoryes", "Home");
            }
            return View(category);
        }

        public IActionResult Delete(int id)
        {
            var category = dataManager.Categoryes.GetCategoryById(id);
            if (category.Articles.Count > 0)
            {
                return Content($"Невозможно удалить категорию - {category.Name}, т.к. есть статьи в этой категории.");
            }

            dataManager.Categoryes.DeleteCategoryById(id);
            return RedirectToAction("Categoryes", "Home");
        }

    }
}

Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using PersonalBlog.Areas.User.Models;

namespace PersonalBlog.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public HomeController(DataManager dataManager, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.dataManager = dataManager;
            this._userManager = userManager;
            this._signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            var user = await _userManager.GetUserAsync(User);

            return View(new ChangePasswordViewModel { Id = user.Id, Email = user.Email });
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Articles()
        {
            if (User.IsInRole("admin"))
            {
                return View(dataManager.Articles.GetArticles());
            }
            else
            {
                var user = await _userManager.GetUserAsync(User);
                return View(dataManager.Articles.GetArticlesByAuthor(user));
            }            
        }

        public IActionResult Categoryes()
        {
            return View(dataManager.Categoryes.GetCategoryes());
        }

        [HttpGet]
        public async Task<IActionResult> Comments()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(dataManager.Comments.GetCommentsByAuthor(user));
        }

    }
}

Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using PersonalBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalBlog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly DataManager dataManager;

        public ArticleController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(int id)
        {
            var article = dataManager.Articles.GetArticleById(id);
            if(article == null)
            {
                return NotFound();
            }

            var tags = dataManager.ArticleWithTags.GetTagsByArticleId(id);
            var comments = dataManager.Comments.GetCommentsByArticleId(id);

            ArticleViewModel viewModel = new ArticleViewModel
            {
                Article = article,
                Tags = tags,
                Comments = comments
            };
            
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Comment(Comment comment)
        {
            dataManager.Comments.SaveComment(comment);
            return RedirectToAction("Index", new { id = comment.ArticleId} );
        }
    }
}

Controllers/UserPersonalInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using PersonalBlog.Models;
using PersonalBlog.Data;
using PersonalBlog.Data.Entities;
using PersonalBlog.Services;

namespace PersonalBlog.Controllers
{
    [Authorize]
    public class UserPersonalInfoController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly DataManager _dataManager;

        public UserPersonalInfoController(UserManager<ApplicationUser> userManager, DataManager dataManager)
        {
            this._userManager = userManager;
            this._dataManager = dataManager;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id = "")
        {
            ApplicationUser user;
            if (id == string.Empty)
            {
                user = await _userManager.GetUserAsync(User);
                ViewData["Title"] = "Изменение личных данных";
            }
            else
            {
                user = await _userManager.FindByIdAsync(id);
                ViewData["Title"] = "Редактирование личных данных пользователя";
            };
               
            if (user == null)
            {
                return NotFound();
            }

            return View(await GetEditUserPersonalInfoViewModel(user));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserPersonalInfoViewModel model, IFormFile userPhotoFile, [FromServices] IWebHostEnvironment hostingEnvironment)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.UserName;

                    if (userPhotoFile != null)
                    {
                        StaticFilesService staticFilesService = new StaticFilesService(hostingEnvironment);
                        user.PhotoPath = staticFilesService.SaveFile(userPhotoFile, "images/");
                    }

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        if (User.IsInRole("admin"))
                            return RedirectToAction("Index", "Users", new { area = "Admin" });
                        else
                            return RedirectToAction("Index", "Home", new { area = "User" });
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        public async Task<EditUserPersonalInfoViewModel> GetEditUserPersonalInfoViewModel(ApplicationUser user)
        {
            return new EditUserPersonalInfoViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                PhotoPath = user.GetPhotoPath()
            };
        }
    }
}

Areas/User/Views/Home/Articles.cshtml
@model IList<Article>
@{
    ViewData["Title"] = "Управление статьями";
}

<p class="h1 text-center">@ViewData["Title"]</p>

<div class="container" style="margin-bottom:15px">
    <a class="btn btn-primary" asp-area="User" asp-controller="Article" asp-action="Edit">Добавить статью</a>
</div>

<p class="h3 text-center">Список статей</p>
<table class="table">
    <thead>
        <tr>
            <th>Статья</th>
            <th>Дата создания</th>
            <th>Автор</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var article in Model)
        {
            <tr>
                <td>
                    <a asp-area="" asp-controller="Article" asp-action="Index" asp-route-id="@article.Id">
                        @($"{article.Title}")
                    </a>
                </td>
                <td>@article.DateAdd</td>
                <td>@article.Author</td>
                <td><a asp-area="User" asp-controller="Article" asp-action="Edit" asp-route-id="@article.Id">Редактировать</a></td>
                <td><a asp-area="User" asp-controller="Article" asp-action="Delete" asp-route-id=@article.Id>Удалить</a></td>
            </tr>
        }
    </tbody>


</table>

Areas/User/Views/Home/Categoryes.cshtml
@model IList<Category>
@{
    ViewData["Title"] = "Управление категориями";
}

<p class="h1 text-center">@ViewData["Title"]</p>

<div class="container" style="margin-bottom:15px">
    <a class="btn btn-primary" asp-area="User" asp-controller="Category" asp-action="Edit">Добавить категорию</a>
</div>

<p class="h3 text-center">Список категорий</p>
<table class="table">
    <thead>
        <tr>
            <th>Категория</th>
            <th>ID</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
        <tr>
            <td>@category.Name</td>
            <td>@category.Id</td>
            @if (User.IsInRole("admin"))
            {
                <td><a asp-area="User" asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id">Редактировать</a></td>
                <td><a asp-area="User" asp-controller="Category" asp-action="Delete" asp-route-id=@category.Id>Удалить</a></td>        
            }              
        </tr>
        }
    </tbody>
</table>

Areas/User/Views/Home/ChangePassword.cshtml
@model ChangePasswordViewModel
@{
    ViewData["Title"] = "Изменение пароля";
}
<h2>@ViewData["Title"]</h2>
<form method="post" asp-area="User" asp-action="ChangePassword" asp-controller="Home">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />
    <div class="form-group">
        <label asp-for="OldPassword" class="control-label">Старый пароль</label>
        <input type="password" asp-for="OldPassword" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">Новый пароль</label>
        <input type="password" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" role="button" />
    </div>
</form>

Areas/User/Views/Home/Comments.cshtml
@model IList<Comment>
@{
    ViewData["Title"] = "Мои комментарии";
}

<p class="h1 text-center">@ViewData["Title"]</p>

<table class="table">
    <thead>
        <tr>
            <th>Статья</th>
            <th>Комментарий</th>
            <th>Дата добавления</th>
            <th>Автор</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in Model)
        {
            <tr>
                <td>
                    <a asp-area="" asp-controller="Article" asp-action="Index" asp-route-id="@comment.Article.Id">
                        @($"{comment.Article.Title}")
                    </a>
                </td>
                <td>@comment.CommentText</td>
                <td>@comment.DateAdd</td>
                <td>@comment.Author</td>
            </tr>
        }
    </tbody>


</table>

Areas/User/Views/Home/Index.cshtml
@model ApplicationUser

@{
    ViewData["Title"] = "Личный кабинет";
}

<p class="h1 text-center">@ViewData["Title"]</p>

<div class="container mb-5 text-center">
    <img src="~/@Model.GetPhotoPath()" alt="" class="rounded-circle avatar">
    <h3>@Model.UserName</h3>
</div>

<div class="list-group">
    <a class="list-group-item" asp-area="" asp-controller="UserPersonalInfo" asp-action="Edit">Изменить личные данные</a>
    <a class="list-group-item" asp-area="User" asp-controller="Home" asp-action="ChangePassword">Изменить пароль</a>
    <a class="list-group-item" asp-area="User" asp-controller="Home" asp-action="Articles">Статьи</a>
    <a class="list-group-item" asp-area="User" asp-controller="Home" asp-action="Categoryes">Категории</a>
    <a class="list-group-item" asp-area="User" asp-controller="Home" asp-action="Comments">Мои комментарии</a>
</div>